### ISSUE TITLE
How to add on a resource?

### ISSUE THREAD

**Issue by Milkhan** [naifalshaye/worldclock#3]
Thank you for this card, but can you explain please, how to add it on a resource?

**Comment by naifalshaye** [comment]
Sorry @Milkhan you can't this is a nova card, not a resource.

**Comment by LorenzoSapora** [comment]
I don't think this is what @Milkhan was meaning. 

Hey Milkhan, you can add this card to a resource by following the installation instructions, but instead of placing the follow in `NovaServiceProvider.php`, you simply put it in your chosen resource.

For example:

```php
// In my User model: App\Nova\User

namespace App\Nova;

[...]
use Naif\WorldClock\WorldClock;

class User extends Resource
{
[...]
    public function cards(Request $request)
    {
        return [
            (new WorldClock())
                ->timezones([
                    'America/Vancouver',
                ])
        ];
    }
[...]
}

```

This also works on Resource, multiple dashboard, or anything with a `function cards()`.

Sorry for reviving an old issue.

**Comment by naifalshaye** [comment]
Thank you @LorenzoSapora
